apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database
        image: mongo:latest
        ports:
        - containerPort: 27017
        volumes:
        - mongodb_data:/data/db   

  volumes:
    mongodb_data:
