apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: server-rollout
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yaml
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: server
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: server
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yaml
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/movies-app-default: "true"
        io.kompose.service: server
    spec:
      containers:
        - env:
            - name: MONGO_HOST
              value: database
            - name: MONGO_PORT
              value: "27017"
          image: harshyadav1309/aiplanet_assignment:server
          name: server
          ports:
            - containerPort: 3000
              hostPort: 3000
              protocol: TCP
      restartPolicy: Always
  strategy:
    canary:
      steps:
        - setWeight: 10
          pause: {}
        - setWeight: 20
          pause: {}
        - setWeight: 30
          pause: {}
        - setWeight: 40
          pause: {}
        - setWeight: 50
          pause: {}
        - setWeight: 60
          pause: {}
        - setWeight: 70
          pause: {}
        - setWeight: 80
          pause: {}
        - setWeight: 90
          pause: {}
        - setWeight: 100
          pause: {}
      trafficRouting:
        istio:
          virtualService:
            name: server