apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: harshyadav1309/aiplanet_assignment:server
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_HOST
          value: database
        - name: MONGO_PORT
          value: "27017"
